version: "3.8"

services:
  webscraping:
    build:
      context: ./webscraping
      dockerfile: Dockerfile
    image: webscraping
    environment:
      DATA_SERVICE_ACCOUNT: ${DATA_SERVICE_ACCOUNT}
      TEXT_GENERATOR: ${TEXT_GENERATOR}
    ports:
      - "8000:8000"  # Adjust port mapping if needed
    command: ["tail", "-f", "/dev/null"] 