version: "3.8"

services:
  webscraping:
    build:
      context: ./webscraping
      dockerfile: Dockerfile
    image: webscraping
    environment:
      DATA_SERVICE_ACCOUNT: ${DATA_SERVICE_ACCOUNT}
      TEXT_GENERATOR: ${TEXT_GENERATOR}
    volumes:
      - ../tests:/app/tests:ro  # Mount the tests directory into the container
    working_dir: /app
    command: ["pipenv", "run", "pytest", "/app/tests/integration_tests/test_webscraping.py"]
    #command: ["tail", "-f", "/dev/null"] 