services:
  webscraping:
    build:
      context: ./webscraping
      dockerfile: Dockerfile
    image: webscraping
    environment:
      DATA_SERVICE_ACCOUNT: ${DATA_SERVICE_ACCOUNT}
      TEXT_GENERATOR: ${TEXT_GENERATOR}
    volumes:
      - ./coverage_data:/app/coverage_data  # Shared directory for coverage files
      - ../tests:/app/tests:ro
      - ./.coveragerc:/app/.coveragerc:ro
    working_dir: /app
    command: tail -f /dev/null

  question_bank:
    build:
      context: ./question_bank
      dockerfile: Dockerfile
    image: question_bank
    environment:
      DATA_SERVICE_ACCOUNT: ${DATA_SERVICE_ACCOUNT}
      TEXT_GENERATOR: ${TEXT_GENERATOR}
    volumes:
      - ./coverage_data:/app/coverage_data  # Shared directory for coverage files
      - ../tests:/app/tests:ro
      - ./.coveragerc:/app/.coveragerc:ro
    working_dir: /app
    command: tail -f /dev/null

  collector:
    image: python:3.11-slim-buster
    volumes:
      - ./coverage_data:/app/coverage_data  # Shared directory for .coverage files
      - ./htmlcov_combined:/app/htmlcov_combined  # Directory for the combined coverage report
      - ./.coveragerc:/app/.coveragerc:ro 
    working_dir: /app
    command: tail -f /dev/null
