name: Integration Tests

on:
  push:
    branches:
      - milestone4
  pull_request:
    branches:
      - milestone4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 3: Test Access to Secrets
    - name: Test Access to Secrets
      run: |
        echo "Testing secrets..."
        echo "$DATA_SERVICE_ACCOUNT" | jq '.' || echo "DATA_SERVICE_ACCOUNT is not valid JSON"
        echo "TEXT_GENERATOR: $TEXT_GENERATOR"
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}

    # Step 4: Build and Start Containers
    - name: Build and start containers
      run: |
        docker-compose -f src/docker-compose.yml up -d
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}

    # Step 5: List Running Containers
    - name: List running Docker containers
      run: docker ps
    
    # Step 5.5: List Running Containers
    - name: Prepare webscraping coverage directory
      run: mkdir -p ./webscraping_coverage
    
    # Step 6: Run Integration Tests for webscraping
    - name: Run integration tests inside webscraping container
      run: |
        docker exec src_webscraping_1 pipenv run coverage run --rcfile=/app/.coveragerc -m pytest /app/tests/integration_tests/test_webscraping.py
        docker exec src_webscraping_1 pipenv run coverage html --rcfile=/app/.coveragerc
        docker cp src_webscraping_1:/app/.coverage ./webscraping_coverage/.coverage
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}
    
    # Step 6.5: List Running Containers
    - name: Prepare question_bank coverage directory
      run: mkdir -p ./question_bank_coverage

    # Step 7: Run Integration Tests for question_bank
    - name: Run integration tests inside question_bank container
      run: |
        docker exec src_question_bank_1 pipenv run coverage run --rcfile=/app/.coveragerc -m pytest /app/tests/integration_tests/test_question_bank.py
        docker exec src_question_bank_1 pipenv run coverage html --rcfile=/app/.coveragerc
        docker cp src_question_bank_1:/app/.coverage ./question_bank_coverage/.coverage
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}

    # Step 9: Stop all containers after tests
    - name: Tear down containers
      if: always()
      run: docker-compose -f src/docker-compose.yml down

    # Step 10: Combine coverage in a unified container
    - name: Combine coverage in temporary container
      run: |
        docker run --rm \
          -v $PWD/webscraping:/app/webscraping:ro \
          -v $PWD/question_bank:/app/question_bank:ro \
          -v $PWD/webscraping_coverage:/app/webscraping_coverage:ro \
          -v $PWD/question_bank_coverage:/app/question_bank_coverage:ro \
          -v $PWD/combined_coverage:/app/combined_coverage \
          python:3.10-slim bash -c "
            pip install coverage &&
            cp /app/webscraping_coverage/.coverage /app/combined_coverage/.coverage.webscraping &&
            cp /app/question_bank_coverage/.coverage /app/combined_coverage/.coverage.question_bank &&
            coverage combine --rcfile=/app/webscraping/.coveragerc /app/combined_coverage/.coverage.webscraping /app/combined_coverage/.coverage.question_bank &&
            coverage html -d /app/combined_coverage
          "

    # Step 11: Debug combined report
    - name: Debug combined coverage report
      run: ls -al ./combined_coverage

    # Step 12: Upload Combined Coverage Report
    - name: Upload combined coverage report
      uses: actions/upload-artifact@v3
      with:
        name: combined-coverage-report
        path: ./combined_coverage

