name: Integration Tests

on:
  push:
    branches:
      - milestone4  # Trigger on pushes to the milestone4 branch
  pull_request:
    branches:
      - milestone4  # Trigger on pull requests to milestone4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Test Access to Secrets
      run: |
        echo "Testing secrets..."
        echo "$DATA_SERVICE_ACCOUNT" | jq '.' || echo "DATA_SERVICE_ACCOUNT is not valid JSON"
        echo "TEXT_GENERATOR: $TEXT_GENERATOR"
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov  # Directly install pytest and pytest-cov

    - name: Build and start containers
      run: |
        docker-compose -f src/docker-compose.yml up -d

    - name: Run integration tests with coverage
      run: pytest --cov=src --cov-report=html --cov-report=term-missing tests/integration_tests
      env:
        DATA_SERVICE_ACCOUNT: ${{ secrets.DATA_SERVICE_ACCOUNT }}
        TEXT_GENERATOR: ${{ secrets.TEXT_GENERATOR }}

    - name: Upload coverage report
      if: always()  # Ensure this always runs, even if the tests fail
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov  # Upload the htmlcov directory

    - name: Tear down containers
      if: always()  # Ensure this always runs, even if the tests fail
      run: docker-compose -f src/docker-compose.yml down
